ENH: Fix a 3D camera within FixedReference frame.
SlicerRt/SlicerRT pull request #252
Opened 2024-09-04 13:22 UTC by MichaelColonel

The corresponding CheckBox widget is added to the "Parameter set" section of the module GUI.

Possible solution for #246.

2024-09-04 13:27 UTC, cpinter commented
Thank you! Please include a video showing the change as you intend it to facilitate the review process.

2024-09-04 14:52 UTC, MichaelColonel commented
Small demo: https://rutube.ru/video/private/1dc1159c438bd62fcb329fad31e1f5b0/?r=wd&p=W7L6xEmfVMXLodEleyoFJw

2024-09-04 14:58 UTC, cpinter commented
Thanks a lot! Do you know why that initial jump happens? (at 19s)

2024-09-04 15:09 UTC, MichaelColonel commented
I don't know the reason.

I've noticed that bug, for some reason it jumps only first time when transform node is updated, and it doesn't jump any longer, even if the check box is unchecked and checked once again.

2024-09-04 22:21 UTC, lassoan commented
It looks very nice!

I've also noticed some transient jumping around while the slider is moved. You can prevent that by calling `pauseRender`, update all the transforms, then call `resumeRender`.

2024-09-05 11:51 UTC, MichaelColonel commented
> You can prevent that by calling `pauseRender`, update all the transforms, then call `resumeRender`.

I will try to test that.

2024-09-10 14:06 UTC, MichaelColonel commented
Most problems are fixed.
Small Demo2 : https://rutube.ru/video/private/7e73c212d9cc3e740a74bf8e0a3ad585/?r=wd&p=UkxnpbJlpIfw4qA_28JQoA

2024-09-10 14:07 UTC, MichaelColonel commented
Ready to review and testing.

2024-09-18 12:17 UTC, cpinter requested changes
Sorry for the delay! I tested the branch and it works great! I just added two very small comments about the code. Thank you very much!

2024-09-18 12:17 UTC, cpinter commented on RoomsEyeView/qSlicerRoomsEyeViewModuleWidget.cxx
> +  qMRMLThreeDView* threeDView = layoutManager->threeDWidget(0)->threeDView();
Please check threeViewCount and if it is 0 return nullptr here.

2024-09-18 12:17 UTC, cpinter commented on RoomsEyeView/qSlicerRoomsEyeViewModuleWidget.cxx
> +  vtkNew<vtkMatrix4x4> transformMatrix;
Give this transform a meaningful name please

2024-09-19 14:14 UTC, MichaelColonel commented
Fixes were added.

2024-09-19 15:22 UTC, merged

2024-09-19 15:22 UTC, cpinter commented
Perfect, thank you so much!

2024-09-23 10:56 UTC, ferdymercury commented
Thanks a lot for the implementation Michael and Csaba/lassoan for the review.